const QUEUE_ACTION = {
	ENVIA_PAGAMENTO: 'ENVIA_PAGAMENTO',
	NOTIFICA_CLIENTE: 'NOTIFICA_CLIENTE',
	PRODUTOS_RESERVADOS: 'PRODUTOS_RESERVADOS',
	SEM_ESTOQUE_PRODUTO: 'SEM_ESTOQUE_PRODUTO',
	PROCEED_PAGAMENTO: 'PROCEED_PAGAMENTO',
};

export default QUEUE_ACTION;