const QUEUE_ACTION = {
	ENVIA_PAGAMENTO: 'ENVIA_PAGAMENTO',
	NOTIFICA_CLIENTE: 'NOTIFICA_CLIENTE',
	PRODUTOS_RESERVADOS: 'PRODUTOS_RESERVADOS',
	SEM_ESTOQUE_PRODUTO: 'SEM_ESTOQUE_PRODUTO',
	// SEND_TO_PAYMENT: 'SEND_TO_PAYMENT',
	RECEIVED_FROM_PAYMENT: 'RECEIVED_FROM_PAYMENT',
	PAYMENT_ERROR: 'PAYMENT_ERROR',
};

export default QUEUE_ACTION;